services:
  # 🗄️ Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine
    container_name: streamview_db
    environment:
      POSTGRES_DB: project_freedom
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d project_freedom" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # 🌐 Aplicação Web (Backend API + Frontend estático)
  app:
    build: .
    container_name: streamview_app
    ports:
      - "80:3001" # [Porta Externa (80)] : [Porta Interna (3001)]
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/project_freedom?schema=public
      - NODE_ENV=production
      - PORT=3001
    restart: always

volumes:
  postgres_data:
